### ISSUE TITLE
Question about license and newest source code

### ISSUE THREAD

**Issue by agehrke** [jcore/JCore.SitecoreModules.ImageCropping#6]
Hi Julia

For the project I'm currently working on we have been discussing implementing exactly the feature that JCore.SitecoreModules.ImageCropping provides. I have tried the 3.0 version from Sitecore marketplace, and would like to extend the functionality further. However the code in the Sitecore package does not seem to correspond with what's here on Github. Would you be willing to publish the latest code?
provides. I have tried the 3.0 version from Sitecore marketplace, and would like to extend the functionality further. However the code in the Sitecore package does not seem to correspond with what's here on Github. Would you be willing to publish the latest code?

As we want to include this module, and hopefully extend it, for our customer's Sitecore solution, I need to ensure that we are not voilating any license conditions. Can you provide information on which license you have published the code in this repository?

/Andreas

**Comment by jcore** [comment]
Hi Andreas,

I don't think there is any licensing issues. I'll update the package and let you know when it is in.

Best regards,
Julia

**Comment by agehrke** [comment]
Great, thank you Julia. So we have your permission to use the code and extend it if needed?

**Comment by jcore** [comment]
Hi Andreas,

Yes, you have permissions to use and extend the code.

**Comment by agehrke** [comment]
Thanks, and I see you pushed latest code.

I'm hoping we can send you a PR later.
